# Generated by Django 4.0.4 on 2022-06-27 08:54

import apps.books.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('cover', models.ImageField(blank=True, upload_to=apps.books.models.book_directory_path)),
                ('desc', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.author')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='eBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ebook_version', models.IntegerField(default=0, unique=True)),
                ('upload_at', models.DateTimeField(auto_now_add=True)),
                ('ebook_file', models.FileField(upload_to='books/txt/')),
                ('chapter_num', models.IntegerField(default=0)),
                ('total_lines', models.IntegerField(default=0)),
                ('is_available', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_index', models.IntegerField(default=0, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('start_line', models.IntegerField(default=0, unique=True)),
                ('slice_file', models.FilePathField(path='books/txt/')),
                ('ebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.ebook')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='cate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.category'),
        ),
    ]
